version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: "${CONTAINER DOCKER}}"
    restart: always
    environment:
      POSTGRES_USER: "${USER_DATABASE}}"
      POSTGRES_PASSWORD: "${PASSWORD_DATABASE}}"
      POSTGRES_DB: "${DATABASE}}"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
